services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./website
    ports:
      - "3000:3000"
    depends_on:
      - backend
