services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    develop:
      watch:
        - action: rebuild
          path: ./backend

  frontend:
    build:
      context: ./website
    ports:
      - "3000:3000"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./website
          target: /app
        - action: rebuild
          path: ./website/package.json
