services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend